### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by allymparker** [kaisunc/vscodevimacademy#10]
I'm getting the following when I try and start the app from the command palette:

![image](https://user-images.githubusercontent.com/2056009/120815383-a9f9c380-c547-11eb-81c2-4671003b8c26.png)

`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

Version: 1.56.2 (system setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by kaisunc** [comment]
I'm not sure what's going on here, but stackoverflow seems to suggest it's
an error introduced in 1.56, and I'm leaning towards this as well.

This is a known bug in VS Code 1.56
<https://github.com/microsoft/vscode/issues/122951>. It happens for some
Windows users when running VS Code as an administrator

As a workaround, you can try launching VS Code with the --no-sandbox command
line flag:

$ code --no-sandbox


It's suggested to NOT run in elevated permissions. Regardless, try running
in both, administrator mode and normal mode. For windows, edit the vscode
shortcut or run code --no-sandbox in the command line.

Other things you can try,

   1. try insiders edition
   2. reinstall vscode
   3. try a clean vscode install with vscode vim and vva
   4. downgrade vscode and downgrade vva

if all else fails, maybe just wait for the next vscode update and see if it
resolves itself.
