### ISSUE TITLE
Is https://github.com/asvetliakov/vscode-neovim supported?

### ISSUE THREAD

**Issue by David-Else** [kaisunc/vscodevimacademy#12]
Hi, awesome plugin!

It works with https://github.com/asvetliakov/vscode-neovim , but the behaviour is very buggy. The cursor often jumps away from where it is meant to be and then the level won't end. Also the graphics draw on top of themselves. It is barely usable.

Also, I get this error sometimes:
![Screenshot from 2021-06-28 15-45-32](https://user-images.githubusercontent.com/12832280/123656560-f1622f80-d827-11eb-8aaf-029a7264967a.png)

**Comment by kaisunc** [comment]
thanks, i've only tested it on neovim once so i can't really add much to
it. I'll add neovim into the test pipeline in the future.

**Comment by gatlinnewhouse** [comment]
Was neovim support added?
