### ISSUE TITLE
Lisence?

### ISSUE THREAD

**Issue by Smashingkeyboard** [kaisunc/vscodevimacademy#13]
How do I get a license after I buy the game?

**Comment by kaisunc** [comment]
a license file will be sent to your paypal email address after purchasing. its a n automated system.

**Comment by Smashingkeyboard** [comment]
> a license file will be sent to your paypal email address after purchasing. its a n automated system.

Would you confirm the transaction "8XW43390LL6706342" and resend the email, since I did not receive any email(@163.com). Thank You!
The game is awesome! The step-by-step training makes it easier for me to change my habits and build muscle memory.

**Comment by kaisunc** [comment]
sorry, there's no transaction id with  8XW43390LL6706342 on paypals
transaction details page. You can also check if your transfer went through
correctly on paypals transaction details page as well.
