### ISSUE TITLE
Other ways to pay?

### ISSUE THREAD

**Issue by yentingli** [kaisunc/vscodevimacademy#14]
Hi,
I want to buy the license, but I can't do it through PayPal (I'm in Taiwan).
Does there any other ways to do it?

**Comment by kaisunc** [comment]
I think you can sign up for a paypal account and pay with a credit or debit
card.
Or is it because Paypal Taiwan can't process the payment?

**Comment by yentingli** [comment]
Info shown by PayPal when I choose Taiwan: 

> We're sorry, due to government regulations, buyers having a billing address in Taiwan cannot use PayPal to make payments to sellers registered in Taiwan.

I walkaround by choose other country. It seems worked.

**Comment by kaisunc** [comment]
thanks, i'll have to look into a local payment method.

**Comment by ycpss91255** [comment]
HI
I encountered the same problem, is there a solution?

**Comment by kaisunc** [comment]
email me at ***@***.***, I'll send you a license for free. I
don't think I'll ever get enough local paying users to justify implementing
a local payment option.

**Comment by ycpss91255** [comment]
thanks you
My mail is ycpss91255@gmail.com

**Comment by dontw** [comment]
Hi, just found this extension and really love it!
Is there any payment option for user in Taiwan now? thanks!
My email is [lawtrooper@gmail.com](mailto:lawtrooper@gmail.com)
