### ISSUE TITLE
Some text dont fully load on the console side when using es Language option

### ISSUE THREAD

**Issue by CorvoHisui** [kaisunc/vscodevimacademy#16]
(edit) sorry i just read is not fully implemented

![image](https://user-images.githubusercontent.com/66727231/146333812-22a72d91-c00d-420b-8eb6-958f9b1ed75d.png)
![image](https://user-images.githubusercontent.com/66727231/146333923-bf8801da-5ca9-4b15-a997-69783f4d0080.png)

**Comment by kaisunc** [comment]
yeah, spanish isn't available yet.
