### ISSUE TITLE
It doesn't work at all?

### ISSUE THREAD

**Issue by twirley** [kaisunc/vscodevimacademy#17]
Hi,
I can install and start it. And I can open in the console the different levels.
But I can't do any of the actions.
I can click on the text and select it. But pressing any button will result in the letter showing up for a split second, to get deleted after.

So I can't do any of the levels.  
pressing h or l - or any other buttons won't move or do anything it is supposed to do...

I can click next to the carret and it moves.. but I would rather try the vim keys

https://user-images.githubusercontent.com/71321660/192201847-e75dc9f7-4349-47d9-afc6-24d7dc2dcb40.mp4

**Comment by kaisunc** [comment]
you need to install the vscode vim extension as well.
