### ISSUE TITLE
Game is not loading

### ISSUE THREAD

**Issue by makarichevss** [kaisunc/vscodevimacademy#2]
Game is not loading.
I have vim extension installed.
![2021-04-03_12-28-36](https://user-images.githubusercontent.com/62963044/113474580-60bec200-9479-11eb-84ab-4d21bf4feeb1.jpg)

**Comment by kaisunc** [comment]
might be a language bug. i had intended to add multi language support and
russian is not one of them.
i'll remove language support on the next patch. In the mean time, you can
try again with english version, sorry about that. it'll be patched tommorow
at the latest

**Comment by kaisunc** [comment]
you can also try manually set vva language to en,
1. go to settings(ui)
2. search for vva
3. under language, set to en
reload, restart vscode see if it works.

**Comment by makarichevss** [comment]
> you can also try manually set vva language to en,
> 
> 1. go to settings(ui)
> 2. search for vva
> 3. under language, set to en
>    reload, restart vscode see if it works.

Thank you - that worked!
So it's up to you - you can keep multi-language support, but please add comment that if anyone has an error like mine, he should set language setting from auto to any other one - and everything will be OK.

P.S. And I decided to show you my appreciation)

**Comment by gerrywastaken** [comment]
Just had the same error message, however without the undefined. This error message should probably be granular.

**Comment by kaisunc** [comment]
fixed in version 1.1.7
