### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by TechnologyClassroom** [kaisunc/vscodevimacademy#3]
Will the code ever be published or is this repository just an issue tracker?

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by kaisunc** [comment]
issue tracker for now. i'll publish the code in the future when i give up
on monetizing this extension/game.

**Comment by TechnologyClassroom** [comment]
I will check back in at a later time then.

It is also does not have to be an either/or situation.  Keeping the present system while publishing the code would keep most people from accessing the content without payment.

**Comment by gerrywastaken** [comment]
@TechnologyClassroom until somebody forks it to bypass the restriction.

**Comment by TechnologyClassroom** [comment]
That could happen, but it usually does not.  Maintaining a project (even a libre fork of another project) is a lot of work.
