### ISSUE TITLE
Typo in Up & Down 1

### ISSUE THREAD

**Issue by EdsellJ** [kaisunc/vscodevimacademy#4]
On _Up & Down 1_ It says that 'j' moves up and 'k' moves down when it is the opposite.

See here:
![image](https://user-images.githubusercontent.com/43834943/116952418-7ae9ec80-ac3f-11eb-877d-3a42c1b83dbb.png)

**Comment by EdsellJ** [comment]
This is actually present in all levels that have 'move up' and 'move down'

**Comment by kaisunc** [comment]
fixed
