### ISSUE TITLE
Level 'Word Search 3' incorrect setup

### ISSUE THREAD

**Issue by jak-ch-ll** [kaisunc/vscodevimacademy#6]
Hi there,

first off, thank you very much for creating the extension, it really helped me to get into VIM and  I bought the premium license to learn more and support such an awesome project.

In the premium section there are a few levels that not work for seemingly different reasons, so I decided to create separate Issues here for each of them.

The first one is 'Word Search 3' in the first section. This one teaches the commands '#' and '*' for jumping to the next occurrence of the word currently under the cursor. The issue is, the level-setup does not create the option to use these commands, since it has the same block of text as the 2 levels before it and you need works that are separated by whitespace or non-letter-characters.

![image](https://user-images.githubusercontent.com/56225668/120454155-eb497200-c393-11eb-8847-5212479e8dfb.png)

Easiest fix would probably be to replace the capital filler letters with spaces or non-letter-chars.

**Comment by kaisunc** [comment]
thanks for the detailed synopsis. It's now fixed, just added spaces surrounding the words to separate them. Not the prettiest, but it'll do for now.
