### ISSUE TITLE
Levels 'Goto Definition' and 'Rename Symbol' not loading

### ISSUE THREAD

**Issue by jak-ch-ll** [kaisunc/vscodevimacademy#7]
The levels 'Goto Defintion' in section 1 and 'Rename Symbol' in section 2 do not load at all for me.

- the level window on the left side just shows whichever level was opened before
- if you open it as the first level after starting VVA, the left side is empty
- the level select on the right does not switch to the level controls

The issue is the same for me on 2 different systems, both Windows 10 and the latest version of VS-Code.

Loading after Word Search 3:
![image](https://user-images.githubusercontent.com/56225668/120454860-8e9a8700-c394-11eb-9cd8-1086942d70c3.png)

Loading from fresh start:
![image](https://user-images.githubusercontent.com/56225668/120455321-f51fa500-c394-11eb-8690-fafa6f61ea6a.png)

**Comment by kaisunc** [comment]
thanks again, I fixed the issue causing the text file not loading.
note to self: ts file ignored in publish directory
