### ISSUE TITLE
Level 'Marks' not loading correctly

### ISSUE THREAD

**Issue by jak-ch-ll** [kaisunc/vscodevimacademy#8]
The level 'Marks' in the first section does not open correctly for me.

- the left window loads something (not sure if it is the correct level)
- the level select on the right does not switch to the level control windows

Tested on 2 different systems, both Win10 and latest version of VScode.

![image](https://user-images.githubusercontent.com/56225668/120455714-4af44d00-c395-11eb-8e1a-773d0dbdcdbf.png)

**Comment by kaisunc** [comment]
thanks, its fixed, should be in the next update,

note to self: activetexteditor needs to be attached to task at buildTasks for prebuilt tasks.
