### ISSUE TITLE
Level 'Swap Characters' breaks VVA

### ISSUE THREAD

**Issue by jak-ch-ll** [kaisunc/vscodevimacademy#9]
The level 'Swap Characters' in section 2 does break VVA for me after opening.

- level window on the left loads something
- select window on the right does not change after clicking
- after loading, it's not possible to change levels anymore or do anything else in VVA

Tested on 2 different systems, both Win10 and latest version of VScode.

After loading the level:
![image](https://user-images.githubusercontent.com/56225668/120456798-3c5a6580-c396-11eb-8069-71ac9e5feeb7.png)

Clicking on another level (that normally works) does nothing:
![image](https://user-images.githubusercontent.com/56225668/120456966-5f851500-c396-11eb-81fb-dd65ac7c3677.png)

**Comment by kaisunc** [comment]
looks like i haven't implemented this level yet, totally forgot about this and left it in the config file. i'll take it out and add it back after.
